#!/bin/sh

# get pyro pid:
pyropid=$1
shift
if [ "$1" = "-g" ]
then
    shift
fi
if [ "$1" = "" ]
then
    
driver="rosaria RosAria"

else

IFS=" " read driver node < $1
    
fi
# start Ros
roscore &
# get Ros pid
ppid=$!

rosrun $driver $node &
# get Ros pid
ppid2=$!


# wait till pyro stops
while ps --noheaders $pyropid; do sleep 1; done > /dev/null
# then kill Ros
#rosnode kill /$node
pkill -SIGINT $node
pkill -SIGINT roscore
